# Generated by Django 6.0.3 on 2026-03-19 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_comments_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('time_favorited', models.DateTimeField(auto_now_add=True)),
                ('article_favorited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_articles', to='news.article')),
                ('user_that_favorited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_that_favorited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
